function synchrony = analyze_organoid_synchrony(activity, varargin)
% Short-lag timing of population MFR events.
% Counts every cross-organoid peak pair in a signed lag window and compares
% the largest post-trigger bin with circular time-shift nulls. Peaks come
% from analyze_organoid_activity. Burst-rate synchrony, not causality.

p = inputParser;
p.addRequired('activity', @isstruct);
p.addParameter('DelayBinSec', 0.05, ...
    @(x) isnumeric(x) && isscalar(x) && x > 0);
p.addParameter('MaxLagSec', 1, @(x) isnumeric(x) && isscalar(x) && x > 0);
p.addParameter('NumCircularShifts', 500, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 1 && mod(x, 1) == 0);
p.addParameter('RandomSeed', 1, ...
    @(x) isnumeric(x) && isscalar(x) && x >= 0 && mod(x, 1) == 0);
p.parse(activity, varargin{:});
opts = p.Results;

requiredFields = {'organoidLabels', 'peakTimesSec', 'parameters'};
missingFields = setdiff(requiredFields, fieldnames(activity));
if ~isempty(missingFields)
    error('analyze_organoid_synchrony:InvalidActivity', ...
        'activity is missing: %s.', strjoin(missingFields, ', '));
end
labels = string(activity.organoidLabels(:));
if numel(labels) ~= 2 || numel(activity.peakTimesSec) ~= 2
    error('analyze_organoid_synchrony:ExpectedTwoOrganoids', ...
        'Synchrony analysis currently requires exactly two organoids.');
end
if opts.DelayBinSec > opts.MaxLagSec
    error('analyze_organoid_synchrony:BinExceedsWindow', ...
        'DelayBinSec must not exceed MaxLagSec.');
end
if ~isfield(activity.parameters, 'RecordingDurationSec') || ...
        ~isscalar(activity.parameters.RecordingDurationSec) || ...
        activity.parameters.RecordingDurationSec <= 0
    error('analyze_organoid_synchrony:MissingDuration', ...
        'activity.parameters.RecordingDurationSec must be a positive scalar.');
end

durationSec = double(activity.parameters.RecordingDurationSec);
peakTimesSec = timingPeakTimes(activity);
[pairs12, histogram12] = postTriggerPairs(peakTimesSec{1}, peakTimesSec{2}, ...
    labels(1), labels(2), opts.DelayBinSec, opts.MaxLagSec);
[pairs21, histogram21] = postTriggerPairs(peakTimesSec{2}, peakTimesSec{1}, ...
    labels(2), labels(1), opts.DelayBinSec, opts.MaxLagSec);
signedHistogramTable = signedPairHistogram(peakTimesSec{1}, peakTimesSec{2}, ...
    labels(1), labels(2), opts.DelayBinSec, opts.MaxLagSec);

stream = RandStream('mt19937ar', 'Seed', opts.RandomSeed);
nullGlobalMaximumPairCount = zeros(opts.NumCircularShifts, 1);
for iShift = 1:opts.NumCircularShifts
    offsetSec = rand(stream) * durationSec;
    shiftedOrganoid2TimesSec = sort(mod(peakTimesSec{2} + offsetSec, durationSec));
    [~, shiftedHistogram12] = postTriggerPairs(peakTimesSec{1}, ...
        shiftedOrganoid2TimesSec, labels(1), labels(2), opts.DelayBinSec, opts.MaxLagSec);
    [~, shiftedHistogram21] = postTriggerPairs(shiftedOrganoid2TimesSec, ...
        peakTimesSec{1}, labels(2), labels(1), opts.DelayBinSec, opts.MaxLagSec);
    nullGlobalMaximumPairCount(iShift) = max([ ...
        shiftedHistogram12.peakPairCount; shiftedHistogram21.peakPairCount]);
end
nullGlobalMaximum95 = empiricalQuantile(nullGlobalMaximumPairCount, 0.95);

directionalSummaryTable = [directionSummary(histogram12, pairs12, ...
    numel(peakTimesSec{1}), nullGlobalMaximumPairCount, nullGlobalMaximum95); ...
    directionSummary(histogram21, pairs21, ...
    numel(peakTimesSec{2}), nullGlobalMaximumPairCount, nullGlobalMaximum95)];
observedGlobalMaximumPairCount = max(directionalSummaryTable.modalPairCount);
globalEmpiricalPValue = (1 + nnz(nullGlobalMaximumPairCount >= ...
    observedGlobalMaximumPairCount)) / (opts.NumCircularShifts + 1);

synchrony = struct();
synchrony.parameters = struct('DelayBinSec', opts.DelayBinSec, ...
    'MaxLagSec', opts.MaxLagSec, 'NumCircularShifts', opts.NumCircularShifts, ...
    'RandomSeed', opts.RandomSeed);
synchrony.organoidLabels = labels;
synchrony.summaryTable = table(labels(1), labels(2), numel(peakTimesSec{1}), ...
    numel(peakTimesSec{2}), opts.DelayBinSec, opts.MaxLagSec, ...
    opts.NumCircularShifts, nullGlobalMaximum95, observedGlobalMaximumPairCount, ...
    globalEmpiricalPValue, observedGlobalMaximumPairCount > nullGlobalMaximum95, ...
    'VariableNames', {'organoid1', 'organoid2', 'organoid1PeakCount', ...
    'organoid2PeakCount', 'delayBinSec', 'maxLagSec', 'numCircularShifts', ...
    'nullGlobalMaximum95', 'observedGlobalMaximumPairCount', ...
    'globalEmpiricalPValue', 'isSignificantAt95'});
synchrony.directionalSummaryTable = directionalSummaryTable;
synchrony.postTriggerPairTable = [pairs12; pairs21];
synchrony.postTriggerHistogramTable = [histogram12; histogram21];
synchrony.signedHistogramTable = signedHistogramTable;
synchrony.nullGlobalMaximumPairCount = nullGlobalMaximumPairCount;
end

function peakTimesSec = timingPeakTimes(activity)
if isfield(activity, 'timingPeakTimesSec') && ...
        numel(activity.timingPeakTimesSec) == 2
    peakTimesSec = activity.timingPeakTimesSec;
else
    peakTimesSec = activity.peakTimesSec;
end
peakTimesSec = {sort(double(peakTimesSec{1}(:))); ...
    sort(double(peakTimesSec{2}(:)))};
end

function [pairTable, histogramTable] = postTriggerPairs( ...
        sourceTimesSec, targetTimesSec, sourceLabel, targetLabel, binSec, maxLagSec)
% Count all target events after every source event in the chosen lag range.

pairTable = emptyPairTable();
for iSource = 1:numel(sourceTimesSec)
    delaySec = targetTimesSec - sourceTimesSec(iSource);
    targetIndices = find(delaySec > 0 & delaySec <= maxLagSec);
    if isempty(targetIndices)
        continue;
    end
    nPairs = numel(targetIndices);
    pairTable = [pairTable; table( ... %#ok<AGROW>
        repmat(sourceLabel, nPairs, 1), repmat(targetLabel, nPairs, 1), ...
        repmat(iSource, nPairs, 1), targetIndices, ...
        repmat(sourceTimesSec(iSource), nPairs, 1), ...
        targetTimesSec(targetIndices), delaySec(targetIndices), ...
        'VariableNames', pairTable.Properties.VariableNames)];
end

binEdgesSec = (0:binSec:maxLagSec).';
if binEdgesSec(end) < maxLagSec
    binEdgesSec(end + 1) = maxLagSec;
end
pairCount = histcounts(pairTable.targetDelaySec, binEdgesSec).';
binStartSec = binEdgesSec(1:end - 1);
binEndSec = binEdgesSec(2:end);
binCenterSec = (binStartSec + binEndSec) / 2;
histogramTable = table(repmat(sourceLabel, numel(pairCount), 1), ...
    repmat(targetLabel, numel(pairCount), 1), binStartSec, binEndSec, ...
    binCenterSec, pairCount, pairCount / max(numel(sourceTimesSec), 1), ...
    'VariableNames', {'sourceOrganoid', 'targetOrganoid', 'delayBinStartSec', ...
    'delayBinEndSec', 'delayBinCenterSec', 'peakPairCount', ...
    'sourcePeakFraction'});
end

function histogramTable = signedPairHistogram( ...
        sourceTimesSec, targetTimesSec, sourceLabel, targetLabel, binSec, maxLagSec)
% Positive delay means target follows source; this is the all-pairs CCG.

delaySec = targetTimesSec.' - sourceTimesSec;
delaySec = delaySec(abs(delaySec) <= maxLagSec);
binEdgesSec = (-maxLagSec:binSec:maxLagSec).';
if binEdgesSec(end) < maxLagSec
    binEdgesSec(end + 1) = maxLagSec;
end
pairCount = histcounts(delaySec, binEdgesSec).';
binStartSec = binEdgesSec(1:end - 1);
binEndSec = binEdgesSec(2:end);
histogramTable = table(repmat(sourceLabel, numel(pairCount), 1), ...
    repmat(targetLabel, numel(pairCount), 1), binStartSec, binEndSec, ...
    (binStartSec + binEndSec) / 2, pairCount, ...
    'VariableNames', {'sourceOrganoid', 'targetOrganoid', 'lagBinStartSec', ...
    'lagBinEndSec', 'lagBinCenterSec', 'peakPairCount'});
end

function summaryTable = directionSummary( ...
        histogramTable, pairTable, sourcePeakCount, nullGlobalMaximumPairCount, ...
        nullGlobalMaximum95)
[modalPairCount, modalIndex] = max(histogramTable.peakPairCount);
modalDelaySec = histogramTable.delayBinCenterSec(modalIndex);
sourcePeaksWithTarget = numel(unique(pairTable.sourcePeakNumber));
empiricalPValue = (1 + nnz(nullGlobalMaximumPairCount >= modalPairCount)) / ...
    (numel(nullGlobalMaximumPairCount) + 1);
summaryTable = table(histogramTable.sourceOrganoid(1), ...
    histogramTable.targetOrganoid(1), sourcePeakCount, sourcePeaksWithTarget, ...
    height(pairTable), modalPairCount, modalDelaySec, nullGlobalMaximum95, ...
    empiricalPValue, modalPairCount > nullGlobalMaximum95, ...
    'VariableNames', {'sourceOrganoid', 'targetOrganoid', 'sourcePeakCount', ...
    'sourcePeaksWithTarget', 'postTriggerPairCount', 'modalPairCount', ...
    'modalDelaySec', 'nullGlobalMaximum95', 'empiricalPValue', ...
    'isSignificantAt95'});
end

function value = empiricalQuantile(values, probability)
values = sort(values(:));
index = max(1, ceil(probability * numel(values)));
value = values(index);
end

function pairTable = emptyPairTable()
pairTable = table(strings(0, 1), strings(0, 1), zeros(0, 1), zeros(0, 1), ...
    zeros(0, 1), zeros(0, 1), zeros(0, 1), ...
    'VariableNames', {'sourceOrganoid', 'targetOrganoid', 'sourcePeakNumber', ...
    'targetPeakNumber', 'sourcePeakTimeSec', 'targetPeakTimeSec', ...
    'targetDelaySec'});
end
